export const GET_EXPENSES = "GET_EXPENSES";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const ADD_EXPENSE = "ADD_EXPENSE";
export const DELETE_EXPENSE = "DELETE_EXPENSE";
export const GET_EXPENSE = "GET_EXPENSE";
